# Generated by Django 5.1.2 on 2024-10-20 23:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='revenue_category',
            new_name='ExpenseCategory',
        ),
        migrations.RenameModel(
            old_name='expense_category',
            new_name='RevenueCategory',
        ),
    ]
